# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_frm.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_frm_main(object):
    def setupUi(self, frm_main):
        if not frm_main.objectName():
            frm_main.setObjectName(u"frm_main")
        frm_main.resize(800, 680)
        self.actionopen = QAction(frm_main)
        self.actionopen.setObjectName(u"actionopen")
        self.actionsave = QAction(frm_main)
        self.actionsave.setObjectName(u"actionsave")
        self.actionsettings = QAction(frm_main)
        self.actionsettings.setObjectName(u"actionsettings")
        self.centralwidget = QWidget(frm_main)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(100, 70, 141, 21))
        font = QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(100, 110, 141, 21))
        self.label_2.setFont(font)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(100, 370, 171, 21))
        self.label_4.setFont(font)
        self.cb_modelauswahl = QComboBox(self.centralwidget)
        self.cb_modelauswahl.setObjectName(u"cb_modelauswahl")
        self.cb_modelauswahl.setGeometry(QRect(460, 470, 271, 22))
        self.cb_modelauswahl.setFont(font)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(100, 510, 211, 21))
        self.label_6.setFont(font)
        self.tb_suche_uid = QLineEdit(self.centralwidget)
        self.tb_suche_uid.setObjectName(u"tb_suche_uid")
        self.tb_suche_uid.setGeometry(QRect(520, 70, 211, 21))
        self.tb_suche_name = QLineEdit(self.centralwidget)
        self.tb_suche_name.setObjectName(u"tb_suche_name")
        self.tb_suche_name.setGeometry(QRect(520, 110, 211, 21))
        self.tb_suche_sn = QLineEdit(self.centralwidget)
        self.tb_suche_sn.setObjectName(u"tb_suche_sn")
        self.tb_suche_sn.setGeometry(QRect(450, 370, 281, 21))
        self.lb_datum_anzeige = QLabel(self.centralwidget)
        self.lb_datum_anzeige.setObjectName(u"lb_datum_anzeige")
        self.lb_datum_anzeige.setGeometry(QRect(650, 40, 141, 20))
        self.lb_datum_anzeige.setFont(font)
        self.lb_datum_anzeige.setLayoutDirection(Qt.LeftToRight)
        self.lb_datum_anzeige.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lb_uid_ausgabe = QLabel(self.centralwidget)
        self.lb_uid_ausgabe.setObjectName(u"lb_uid_ausgabe")
        self.lb_uid_ausgabe.setGeometry(QRect(280, 70, 201, 21))
        self.lb_uid_ausgabe.setFont(font)
        self.lb_name_ausgabe = QLabel(self.centralwidget)
        self.lb_name_ausgabe.setObjectName(u"lb_name_ausgabe")
        self.lb_name_ausgabe.setGeometry(QRect(280, 110, 201, 21))
        self.lb_name_ausgabe.setFont(font)
        self.notiz_eingabe = QLineEdit(self.centralwidget)
        self.notiz_eingabe.setObjectName(u"notiz_eingabe")
        self.notiz_eingabe.setGeometry(QRect(100, 540, 621, 51))
        self.lb_9 = QLabel(self.centralwidget)
        self.lb_9.setObjectName(u"lb_9")
        self.lb_9.setGeometry(QRect(100, 470, 251, 21))
        self.lb_9.setFont(font)
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(640, 430, 91, 22))
        self.lb_8 = QLabel(self.centralwidget)
        self.lb_8.setObjectName(u"lb_8")
        self.lb_8.setGeometry(QRect(100, 430, 171, 21))
        self.lb_8.setFont(font)
        self.btn_settings = QPushButton(self.centralwidget)
        self.btn_settings.setObjectName(u"btn_settings")
        self.btn_settings.setGeometry(QRect(10, 0, 75, 24))
        self.btn_export = QPushButton(self.centralwidget)
        self.btn_export.setObjectName(u"btn_export")
        self.btn_export.setGeometry(QRect(630, 600, 91, 24))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(100, 180, 151, 21))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(False)
        self.label_9.setFont(font1)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 250, 151, 21))
        self.label_3.setFont(font)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(100, 400, 161, 16))
        self.label_5.setFont(font)
        self.lb_entwickler = QLabel(self.centralwidget)
        self.lb_entwickler.setObjectName(u"lb_entwickler")
        self.lb_entwickler.setGeometry(QRect(640, 400, 91, 16))
        self.lb_entwickler.setFont(font)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(90, 10, 541, 41))
        font2 = QFont()
        font2.setPointSize(22)
        font2.setBold(True)
        self.label_8.setFont(font2)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.lb_kostenstelle = QLabel(self.centralwidget)
        self.lb_kostenstelle.setObjectName(u"lb_kostenstelle")
        self.lb_kostenstelle.setGeometry(QRect(280, 180, 181, 20))
        self.lb_kostenstelle.setFont(font)
        self.lb_hinweis = QLabel(self.centralwidget)
        self.lb_hinweis.setObjectName(u"lb_hinweis")
        self.lb_hinweis.setGeometry(QRect(100, 270, 631, 91))
        font3 = QFont()
        font3.setPointSize(14)
        font3.setBold(True)
        self.lb_hinweis.setFont(font3)
        self.lb_hinweis.setAutoFillBackground(True)
        self.lb_hinweis.setLineWidth(4)
        self.lb_hinweis.setWordWrap(True)
        self.cb_mehr_eintrag = QComboBox(self.centralwidget)
        self.cb_mehr_eintrag.setObjectName(u"cb_mehr_eintrag")
        self.cb_mehr_eintrag.setGeometry(QRect(520, 220, 211, 22))
        self.lb_mehr_eintrag = QLabel(self.centralwidget)
        self.lb_mehr_eintrag.setObjectName(u"lb_mehr_eintrag")
        self.lb_mehr_eintrag.setGeometry(QRect(520, 140, 211, 31))
        self.lb_mehr_eintrag.setFont(font3)
        self.cb_MehrfachNamen = QComboBox(self.centralwidget)
        self.cb_MehrfachNamen.setObjectName(u"cb_MehrfachNamen")
        self.cb_MehrfachNamen.setGeometry(QRect(520, 180, 211, 22))
        self.lb_quatal = QLabel(self.centralwidget)
        self.lb_quatal.setObjectName(u"lb_quatal")
        self.lb_quatal.setGeometry(QRect(280, 210, 141, 31))
        self.lb_quatal.setFont(font)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(100, 220, 151, 21))
        self.label_7.setFont(font)
        self.lb_WenSnVorhanden = QLabel(self.centralwidget)
        self.lb_WenSnVorhanden.setObjectName(u"lb_WenSnVorhanden")
        self.lb_WenSnVorhanden.setGeometry(QRect(270, 370, 171, 21))
        self.lb_WenSnVorhanden.setFont(font3)
        self.lb_WenSnVorhanden.setLayoutDirection(Qt.LeftToRight)
        self.lb_WenSnVorhanden.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lb_AushabeHinweis = QLabel(self.centralwidget)
        self.lb_AushabeHinweis.setObjectName(u"lb_AushabeHinweis")
        self.lb_AushabeHinweis.setGeometry(QRect(100, 540, 621, 51))
        self.lb_AushabeHinweis.setFont(font3)
        frm_main.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(frm_main)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        frm_main.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(frm_main)
        self.statusbar.setObjectName(u"statusbar")
        frm_main.setStatusBar(self.statusbar)

        self.retranslateUi(frm_main)

        QMetaObject.connectSlotsByName(frm_main)
    # setupUi

    def retranslateUi(self, frm_main):
        frm_main.setWindowTitle(QCoreApplication.translate("frm_main", u"AusgabeTool", None))
        self.actionopen.setText(QCoreApplication.translate("frm_main", u"open", None))
        self.actionsave.setText(QCoreApplication.translate("frm_main", u"save", None))
        self.actionsettings.setText(QCoreApplication.translate("frm_main", u"settings", None))
        self.label.setText(QCoreApplication.translate("frm_main", u"UID:", None))
        self.label_2.setText(QCoreApplication.translate("frm_main", u"Name:", None))
        self.label_4.setText(QCoreApplication.translate("frm_main", u"SN:", None))
        self.label_6.setText(QCoreApplication.translate("frm_main", u"Ausgabe Hinweis:", None))
        self.lb_datum_anzeige.setText(QCoreApplication.translate("frm_main", u"Datum", None))
        self.lb_uid_ausgabe.setText(QCoreApplication.translate("frm_main", u"UID", None))
        self.lb_name_ausgabe.setText(QCoreApplication.translate("frm_main", u"Name", None))
        self.lb_9.setText(QCoreApplication.translate("frm_main", u"<html><head/><body><p>Bestelltes Modell ggf. \u00e4ndern in:</p><p><br/></p></body></html>", None))
        self.lb_8.setText(QCoreApplication.translate("frm_main", u"Betriebssystem:", None))
        self.btn_settings.setText(QCoreApplication.translate("frm_main", u"Settings", None))
        self.btn_export.setText(QCoreApplication.translate("frm_main", u"Speichern", None))
        self.label_9.setText(QCoreApplication.translate("frm_main", u"Kostenstelle", None))
        self.label_3.setText(QCoreApplication.translate("frm_main", u"Hinweis", None))
        self.label_5.setText(QCoreApplication.translate("frm_main", u"Entwickler:", None))
        self.lb_entwickler.setText(QCoreApplication.translate("frm_main", u"Ja/Nein", None))
        self.label_8.setText(QCoreApplication.translate("frm_main", u"Hardware Rollout ", None))
        self.lb_kostenstelle.setText(QCoreApplication.translate("frm_main", u"TextLabel", None))
        self.lb_hinweis.setText(QCoreApplication.translate("frm_main", u"TextLabel", None))
        self.lb_mehr_eintrag.setText(QCoreApplication.translate("frm_main", u"Mehrfach gefunden", None))
        self.lb_quatal.setText(QCoreApplication.translate("frm_main", u"TextLabel", None))
        self.label_7.setText(QCoreApplication.translate("frm_main", u"Quartal:", None))
        self.lb_WenSnVorhanden.setText("")
        self.lb_AushabeHinweis.setText(QCoreApplication.translate("frm_main", u"TextLabel", None))
    # retranslateUi

